export const products = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    price: 199.99,
    originalPrice: 249.99,
    rating: 4.8,
    reviewCount: 324,
    image:
      "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=400",
    badge: "Best Seller",
    category: "Electronics",
    description: "High-quality wireless headphones with noise cancellation",
    inStock: true,
    longDescription: "",
    images: [],
    brand: "",
    stockCount: 0,
    variants: {
      colors: undefined,
      sizes: undefined,
    },
    features: [],
    specifications: {},
    tags: [],
  },
  {
    id: "2",
    name: "Leather Crossbody Bag",
    price: 89.99,
    rating: 4.6,
    reviewCount: 156,
    image:
      "https://images.pexels.com/photos/904350/pexels-photo-904350.jpeg?auto=compress&cs=tinysrgb&w=400",
    badge: "New",
    category: "Fashion",
    description: "Stylish leather crossbody bag for everyday use",
    inStock: true,
    longDescription: "",
    images: [],
    brand: "",
    stockCount: 0,
    variants: {
      colors: undefined,
      sizes: undefined,
    },
    features: [],
    specifications: {},
    tags: [],
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    price: 29.99,
    rating: 4.7,
    reviewCount: 89,
    image:
      "https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&w=400",
    category: "Fashion",
    description: "Comfortable organic cotton t-shirt in various colors",
    inStock: true,
    longDescription: "",
    images: [],
    brand: "",
    stockCount: 0,
    variants: {
      colors: undefined,
      sizes: undefined,
    },
    features: [],
    specifications: {},
    tags: [],
    badge: "",
  },
  {
    id: "4",
    name: "Classic Sneakers",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviewCount: 203,
    image:
      "https://images.pexels.com/photos/1464625/pexels-photo-1464625.jpeg?auto=compress&cs=tinysrgb&w=400",
    badge: "Sale",
    category: "Fashion",
    description: "Classic white sneakers perfect for any occasion",
    inStock: true,
    longDescription: "",
    images: [],
    brand: "",
    stockCount: 0,
    variants: {
      colors: undefined,
      sizes: undefined,
    },
    features: [],
    specifications: {},
    tags: [],
  },
  {
    id: "5",
    name: "Smart Watch Series 5",
    price: 299.99,
    rating: 4.9,
    reviewCount: 412,
    image:
      "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=400",
    badge: "Featured",
    category: "Electronics",
    description: "Advanced smartwatch with health tracking features",
    inStock: true,
    longDescription: "",
    images: [],
    brand: "",
    stockCount: 0,
    variants: {
      colors: undefined,
      sizes: undefined,
    },
    features: [],
    specifications: {},
    tags: [],
  },
  {
    id: "6",
    name: "Minimalist Backpack",
    price: 59.99,
    rating: 4.4,
    reviewCount: 67,
    image:
      "https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg?auto=compress&cs=tinysrgb&w=400",
    category: "Fashion",
    description: "Clean, minimalist backpack for work and travel",
    inStock: true,
    longDescription: "",
    images: [],
    brand: "",
    stockCount: 0,
    variants: {
      colors: undefined,
      sizes: undefined,
    },
    features: [],
    specifications: {},
    tags: [],
    badge: "",
  },
  {
    id: "7",
    name: "Bluetooth Speaker",
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.3,
    reviewCount: 128,
    image:
      "https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg?auto=compress&cs=tinysrgb&w=400",
    category: "Electronics",
    description: "Portable Bluetooth speaker with excellent sound quality",
    inStock: true,
    longDescription: "",
    images: [],
    brand: "",
    stockCount: 0,
    variants: {
      colors: undefined,
      sizes: undefined,
    },
    features: [],
    specifications: {},
    tags: [],
    badge: "",
  },
  {
    id: "8",
    name: "Ceramic Coffee Mug",
    price: 19.99,
    rating: 4.2,
    reviewCount: 45,
    image:
      "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=400",
    category: "Home",
    description: "Beautiful ceramic coffee mug with ergonomic handle",
    inStock: true,
    longDescription: "",
    images: [],
    brand: "",
    stockCount: 0,
    variants: {
      colors: undefined,
      sizes: undefined,
    },
    features: [],
    specifications: {},
    tags: [],
    badge: "",
  },
  {
    id: "9",
    name: "Yoga Mat",
    price: 39.99,
    rating: 4.6,
    reviewCount: 234,
    image:
      "https://images.pexels.com/photos/4056723/pexels-photo-4056723.jpeg?auto=compress&cs=tinysrgb&w=400",
    category: "Sports",
    description: "Non-slip yoga mat perfect for all types of exercise",
    inStock: true,
    longDescription: "",
    images: [],
    brand: "",
    stockCount: 0,
    variants: {
      colors: undefined,
      sizes: undefined,
    },
    features: [],
    specifications: {},
    tags: [],
    badge: "",
  },
  {
    id: "10",
    name: "Desk Lamp",
    price: 79.99,
    rating: 4.4,
    reviewCount: 92,
    image:
      "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&w=400",
    category: "Home",
    description: "Modern LED desk lamp with adjustable brightness",
    inStock: false,
    longDescription: "",
    images: [],
    brand: "",
    stockCount: 0,
    variants: {
      colors: undefined,
      sizes: undefined,
    },
    features: [],
    specifications: {},
    tags: [],
    badge: "",
  },
  {
    id: "11",
    name: "Running Shoes",
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.7,
    reviewCount: 189,
    image:
      "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=400",
    badge: "Sale",
    category: "Sports",
    description: "Lightweight running shoes with superior cushioning",
    inStock: true,
    longDescription: "",
    images: [],
    brand: "",
    stockCount: 0,
    variants: {
      colors: undefined,
      sizes: undefined,
    },
    features: [],
    specifications: {},
    tags: [],
  },
  {
    id: "12",
    name: "Wireless Mouse",
    price: 34.99,
    rating: 4.1,
    reviewCount: 76,
    image:
      "https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=400",
    category: "Electronics",
    description: "Ergonomic wireless mouse with precision tracking",
    inStock: true,
    longDescription: "",
    images: [],
    brand: "",
    stockCount: 0,
    variants: {
      colors: undefined,
      sizes: undefined,
    },
    features: [],
    specifications: {},
    tags: [],
    badge: "",
  },
];
